export const ListPostExamples = [
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 1 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 2 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 3 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 4 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 5 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 6 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 7 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 8 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 9 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 10 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 11 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 12 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 12 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
    {       
        id: '1254336985dag',
        img: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder-1024x512.png',
        main_category: 'Sản khoa',
        views_count: 1500,
        comment_count: 25,
        like_count: 100,
        title: 'Kiến thức chăm sóc 12 Days',
        abstract: 'Hiện nay chưa có phương pháp hữu hiệu để điều trị thai chậm phát triển trong tử cung, tùy thuộc vào nguyên nhân và thời gian xuất hiện FGR sớm hay muộn mà tiên lượng và cách xử trí khác nhau. Cần phải theo dõi chặt chẽ và tư vấn kỹ cho sản phụ và gia đình trong giai đoạn mang thai. Có thể điều trị tăng huyết áp nếu xác định đó chính là nguyên nhân gây thai chậm phát triển.',
        author: 'Chanh Ly',
        author_avatar: 'https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg',
        createSignUp: '28 Sep 2020',
        createAt: '9 minutes read',
    },
]

export const PostItemExample = {
    isDraft: false,
    isPublish: true,
    title: 'Loãng xương ở tuổi mãn kinh',
    content: 'Thống kê cho thấy, khoảng 71% phụ nữ trên 50 tuổi bị gãy xương do loãng xương. Sàng lọc và đánh giá nguy cơ giúp tiên lượng biến cố gãy xương trên các đối tượng loãng xương. Sử dụng thuốc giúp phòng ngừa và làm chậm quá trình mất xương.',
    author: 'chanhly'
}

export const ListUser = [
    {
        id: '1542sd',
        name: 'Chanh Ly',
        email: 'neangchanhlyyak35@gmail.com',
        role: 'admin',
        time: 1566651096736,
        avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    },
    {
        id: '1542sd',
        name: 'Minh Hy',
        email: 'MinhHy001@gmail.com',
        role: 'writer',
        time: 1696651096736,
        avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    },
    {
        id: '1542sd',
        name: 'Alex Do',
        email: 'alexdo001@gmail.com',
        role: 'user',
        time: 1666651096736,
        avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    },
]

export const ListCategory = [
    {
        id: '1542sd',
        name: 'y hoc thuong thuc',
        author: 'Chanh Ly',
        totalPost : 12,
        createdAt: 1656651096736,
    },
    {
        id: '1542sd',
        name: 'San khoa',
        author: 'Neang Chanh Ly',
        totalPost : 12,
        createdAt: 1626651096736,
    },
    {
        id: '1542sd',
        name: 'hiem muon',
        author: 'Chanh Ly',
        totalPost : 12,
        createdAt: 1636651096736,
    },
]

export const ListTag = [
    {
        id: '1542sd',
        name: 'mevabe',
        author: 'Chanh Ly',
        totalPost : 12,
        createdAt: 1656651096736,
    },
    {
        id: '1542sd',
        name: 'hiemmuon',
        author: 'Chanh Ly',
        totalPost : 12,
        createdAt: 1626651096736,
    },
    {
        id: '1542sd',
        name: 'sankhoa',
        author: 'Chanh Ly',
        totalPost : 12,
        createdAt: 1636651096736,
    },
    {
        id: '1542sd',
        name: 'phukhoa',
        author: 'Chanh Ly',
        totalPost : 12,
        createdAt: 1636651096736,
    },
    {
        id: '1542sd',
        name: 'anuongtrongthaiki',
        author: 'Chanh Ly',
        totalPost : 12,
        createdAt: 1636651096736,
    },
    {
        id: '1542sd',
        name: 'tambe',
        author: 'Chanh Ly',
        totalPost : 12,
        createdAt: 1636651096736,
    }
]